# Simple workflow for deploying static content to GitHub Pages
name: Deploy 

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']


jobs:
  # Single deploy job since we're just deploying
  deploy:
    name: github-pages
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./dist
      - name: Deploy to GitHub Pages
        
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          publish_dir: ./dist

